/* === DO NOT EDIT THIS FILE! ===
** This code is part of the Web API ASP.net core template. There are a lot of
** macros doing things in the background here. Any logic should be directly
** implemented in the Controllers/ directory. Basically treat any controller as
** its own little main.
*/



// === AUTO-GENERATED CODE AHEAD! ===

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace CeptoApi
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
